### PR TITLE
Adding method to stop a test

### PR DESCRIPTION
**Pull request by meggamind**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-android/12)

### CODE REVIEW

**Comment by meggamind** [comment]
@stephen-soltesz can we add this?

**Review by stephen-soltesz — APPROVED** [review]
Hello, @meggamind ! 

I have no objection to a stop button.

Unfortunately, I don't have experience with Kotlin.

Also, unfortunately, this repo doesn't seem to have any build checks, so I don't know for sure if this breaks anything. I am happy to trust you if you say it's still working. This is community supported.

Would you consider adding any kind of unit or integration testing in the future as a sanity check? e.g. something that would "ratchet up" the code health for this repo and ensure that it does not regress in the future?

:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-android/12#-:-MUG5LwaBjxkdLjWRqAF:b-agtoep)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by meggamind** [comment]
Sure thing I'll look into adding a few tests

**Comment by meggamind** [comment]
@stephen-soltesz I don't have permission to merge, can you please do it? thanks

**Comment by stephen-soltesz** [comment]
@meggamind I've invited you as a collaborator for this repo. This should make some things easier.

General guidelines we all strive for:

* be kind
* make things a little better
* don't break everything at once

Welcome.

**Pull request merged**
